// Account Types following standard accounting principles
export enum AccountType {
  // Assets (Debit increases, Credit decreases)
  ASSET = 'ASSET',
  CURRENT_ASSET = 'CURRENT_ASSET',
  FIXED_ASSET = 'FIXED_ASSET',
  INTANGIBLE_ASSET = 'INTANGIBLE_ASSET',
  
  // Liabilities (Credit increases, Debit decreases)
  LIABILITY = 'LIABILITY',
  CURRENT_LIABILITY = 'CURRENT_LIABILITY',
  LONG_TERM_LIABILITY = 'LONG_TERM_LIABILITY',
  
  // Equity (Credit increases, Debit decreases)
  EQUITY = 'EQUITY',
  RETAINED_EARNINGS = 'RETAINED_EARNINGS',
  CAPITAL = 'CAPITAL',
  
  // Revenue (Credit increases, Debit decreases)
  REVENUE = 'REVENUE',
  OPERATING_REVENUE = 'OPERATING_REVENUE',
  NON_OPERATING_REVENUE = 'NON_OPERATING_REVENUE',
  
  // Expenses (Debit increases, Credit decreases)
  EXPENSE = 'EXPENSE',
  OPERATING_EXPENSE = 'OPERATING_EXPENSE',
  NON_OPERATING_EXPENSE = 'NON_OPERATING_EXPENSE',
  
  // SwiftPayMe Specific Account Types
  USER_WALLET = 'USER_WALLET',
  ESCROW = 'ESCROW',
  RESERVE = 'RESERVE',
  FEE_COLLECTION = 'FEE_COLLECTION',
  SUSPENSE = 'SUSPENSE'
}

// Account Categories for financial reporting
export enum AccountCategory {
  // Balance Sheet Categories
  CASH_AND_EQUIVALENTS = 'CASH_AND_EQUIVALENTS',
  ACCOUNTS_RECEIVABLE = 'ACCOUNTS_RECEIVABLE',
  INVENTORY = 'INVENTORY',
  PREPAID_EXPENSES = 'PREPAID_EXPENSES',
  PROPERTY_PLANT_EQUIPMENT = 'PROPERTY_PLANT_EQUIPMENT',
  ACCOUNTS_PAYABLE = 'ACCOUNTS_PAYABLE',
  ACCRUED_LIABILITIES = 'ACCRUED_LIABILITIES',
  NOTES_PAYABLE = 'NOTES_PAYABLE',
  COMMON_STOCK = 'COMMON_STOCK',
  
  // Income Statement Categories
  SALES_REVENUE = 'SALES_REVENUE',
  SERVICE_REVENUE = 'SERVICE_REVENUE',
  COST_OF_GOODS_SOLD = 'COST_OF_GOODS_SOLD',
  SELLING_EXPENSES = 'SELLING_EXPENSES',
  ADMINISTRATIVE_EXPENSES = 'ADMINISTRATIVE_EXPENSES',
  INTEREST_INCOME = 'INTEREST_INCOME',
  INTEREST_EXPENSE = 'INTEREST_EXPENSE',
  
  // SwiftPayMe Specific Categories
  CRYPTO_ASSETS = 'CRYPTO_ASSETS',
  PRECIOUS_METALS = 'PRECIOUS_METALS',
  TOKENIZED_ASSETS = 'TOKENIZED_ASSETS',
  TRANSACTION_FEES = 'TRANSACTION_FEES',
  CONVERSION_FEES = 'CONVERSION_FEES',
  CUSTODY_FEES = 'CUSTODY_FEES'
}

// Account Status
export enum AccountStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  SUSPENDED = 'SUSPENDED',
  CLOSED = 'CLOSED',
  FROZEN = 'FROZEN',
  UNDER_REVIEW = 'UNDER_REVIEW'
}

// Transaction Types
export enum TransactionType {
  // Basic Transaction Types
  DEBIT = 'DEBIT',
  CREDIT = 'CREDIT',
  TRANSFER = 'TRANSFER',
  
  // SwiftPayMe Business Transactions
  DEPOSIT = 'DEPOSIT',
  WITHDRAWAL = 'WITHDRAWAL',
  ASSET_DEPOSIT = 'ASSET_DEPOSIT',
  ASSET_WITHDRAWAL = 'ASSET_WITHDRAWAL',
  CRYPTO_PURCHASE = 'CRYPTO_PURCHASE',
  CRYPTO_SALE = 'CRYPTO_SALE',
  TOKEN_MINT = 'TOKEN_MINT',
  TOKEN_BURN = 'TOKEN_BURN',
  FEE_COLLECTION = 'FEE_COLLECTION',
  REFUND = 'REFUND',
  ADJUSTMENT = 'ADJUSTMENT',
  REVERSAL = 'REVERSAL',
  
  // Internal Operations
  RECONCILIATION = 'RECONCILIATION',
  REVALUATION = 'REVALUATION',
  PROVISION = 'PROVISION',
  WRITE_OFF = 'WRITE_OFF'
}

// Transaction Status
export enum TransactionStatus {
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED',
  REVERSED = 'REVERSED',
  RECONCILED = 'RECONCILED',
  DISPUTED = 'DISPUTED'
}

// Journal Entry Status
export enum JournalEntryStatus {
  DRAFT = 'DRAFT',
  PENDING_APPROVAL = 'PENDING_APPROVAL',
  APPROVED = 'APPROVED',
  POSTED = 'POSTED',
  REJECTED = 'REJECTED',
  REVERSED = 'REVERSED',
  CANCELLED = 'CANCELLED'
}

// Entry Type for Journal Entries
export enum EntryType {
  STANDARD = 'STANDARD',
  ADJUSTING = 'ADJUSTING',
  CLOSING = 'CLOSING',
  REVERSING = 'REVERSING',
  CORRECTING = 'CORRECTING',
  RECURRING = 'RECURRING'
}

// Debit/Credit Indicator
export enum DebitCredit {
  DEBIT = 'DEBIT',
  CREDIT = 'CREDIT'
}

// Currency Types
export enum CurrencyType {
  FIAT = 'FIAT',
  CRYPTO = 'CRYPTO',
  TOKEN = 'TOKEN',
  COMMODITY = 'COMMODITY'
}

// Reconciliation Status
export enum ReconciliationStatus {
  UNRECONCILED = 'UNRECONCILED',
  RECONCILED = 'RECONCILED',
  PARTIALLY_RECONCILED = 'PARTIALLY_RECONCILED',
  DISPUTED = 'DISPUTED',
  PENDING_REVIEW = 'PENDING_REVIEW'
}

// Audit Event Types
export enum AuditEventType {
  ACCOUNT_CREATED = 'ACCOUNT_CREATED',
  ACCOUNT_UPDATED = 'ACCOUNT_UPDATED',
  ACCOUNT_CLOSED = 'ACCOUNT_CLOSED',
  TRANSACTION_CREATED = 'TRANSACTION_CREATED',
  TRANSACTION_UPDATED = 'TRANSACTION_UPDATED',
  TRANSACTION_CANCELLED = 'TRANSACTION_CANCELLED',
  JOURNAL_ENTRY_POSTED = 'JOURNAL_ENTRY_POSTED',
  JOURNAL_ENTRY_REVERSED = 'JOURNAL_ENTRY_REVERSED',
  BALANCE_ADJUSTMENT = 'BALANCE_ADJUSTMENT',
  RECONCILIATION_PERFORMED = 'RECONCILIATION_PERFORMED',
  REPORT_GENERATED = 'REPORT_GENERATED',
  SYSTEM_BACKUP = 'SYSTEM_BACKUP',
  DATA_EXPORT = 'DATA_EXPORT',
  SECURITY_EVENT = 'SECURITY_EVENT'
}

// Audit Severity Levels
export enum AuditSeverity {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL'
}

// Balance Types
export enum BalanceType {
  CURRENT = 'CURRENT',
  AVAILABLE = 'AVAILABLE',
  PENDING = 'PENDING',
  RESERVED = 'RESERVED',
  FROZEN = 'FROZEN',
  ESCROW = 'ESCROW'
}

// Period Types for Reporting
export enum PeriodType {
  DAILY = 'DAILY',
  WEEKLY = 'WEEKLY',
  MONTHLY = 'MONTHLY',
  QUARTERLY = 'QUARTERLY',
  YEARLY = 'YEARLY',
  CUSTOM = 'CUSTOM'
}

// Report Types
export enum ReportType {
  TRIAL_BALANCE = 'TRIAL_BALANCE',
  BALANCE_SHEET = 'BALANCE_SHEET',
  INCOME_STATEMENT = 'INCOME_STATEMENT',
  CASH_FLOW = 'CASH_FLOW',
  GENERAL_LEDGER = 'GENERAL_LEDGER',
  ACCOUNT_STATEMENT = 'ACCOUNT_STATEMENT',
  TRANSACTION_REPORT = 'TRANSACTION_REPORT',
  RECONCILIATION_REPORT = 'RECONCILIATION_REPORT',
  AUDIT_TRAIL = 'AUDIT_TRAIL',
  REGULATORY_REPORT = 'REGULATORY_REPORT'
}

// Approval Status
export enum ApprovalStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  REQUIRES_ADDITIONAL_APPROVAL = 'REQUIRES_ADDITIONAL_APPROVAL'
}

// Risk Levels
export enum RiskLevel {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  VERY_HIGH = 'VERY_HIGH'
}

// Compliance Status
export enum ComplianceStatus {
  COMPLIANT = 'COMPLIANT',
  NON_COMPLIANT = 'NON_COMPLIANT',
  UNDER_REVIEW = 'UNDER_REVIEW',
  EXEMPTED = 'EXEMPTED'
}

// Error Codes for Ledger Operations
export enum LedgerErrorCode {
  INSUFFICIENT_BALANCE = 'INSUFFICIENT_BALANCE',
  ACCOUNT_NOT_FOUND = 'ACCOUNT_NOT_FOUND',
  ACCOUNT_INACTIVE = 'ACCOUNT_INACTIVE',
  INVALID_TRANSACTION_TYPE = 'INVALID_TRANSACTION_TYPE',
  DUPLICATE_TRANSACTION = 'DUPLICATE_TRANSACTION',
  UNBALANCED_JOURNAL_ENTRY = 'UNBALANCED_JOURNAL_ENTRY',
  UNAUTHORIZED_OPERATION = 'UNAUTHORIZED_OPERATION',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  RECONCILIATION_MISMATCH = 'RECONCILIATION_MISMATCH',
  AUDIT_TRAIL_CORRUPTION = 'AUDIT_TRAIL_CORRUPTION'
}

export default {
  AccountType,
  AccountCategory,
  AccountStatus,
  TransactionType,
  TransactionStatus,
  JournalEntryStatus,
  EntryType,
  DebitCredit,
  CurrencyType,
  ReconciliationStatus,
  AuditEventType,
  AuditSeverity,
  BalanceType,
  PeriodType,
  ReportType,
  ApprovalStatus,
  RiskLevel,
  ComplianceStatus,
  LedgerErrorCode
};

